import { router, useLocalSearchParams } from 'expo-router';
import { Image, ScrollView, StyleSheet, Text, Pressable, View } from 'react-native';
import { authorById } from '@/src/data/authorsData';
import { authorPhotos } from '@/src/data/authorPhotos';
import { useQuoteBank } from '@/src/hooks/useQuoteBank';
import type { Quote } from '@/src/types';
import { colors } from '@/src/theme';

export function AuthorDetail({ authorId }: { authorId: string }): JSX.Element {
  const author = authorById(authorId); const { quotes, saveQuote, removeQuote } = useQuoteBank();
  const goToAuthorsList = () => router.replace('/authors');
  if (!author) return <View style={styles.page}><Pressable accessibilityRole="button" onPress={goToAuthorsList} style={styles.backButton}><Text style={styles.backButtonText}>‹ All Authors</Text></Pressable><Text>Author not found.</Text></View>;
  return <ScrollView contentContainerStyle={styles.page}><Pressable accessibilityRole="button" onPress={goToAuthorsList} style={styles.backButton}><Text style={styles.backButtonText}>‹ All Authors</Text></Pressable><View style={styles.header}><View style={styles.headerText}><Text style={styles.name}>{author.name}</Text><Text style={styles.bio}>{author.bio}</Text></View><View style={styles.photoSlot}>{authorPhotos[author.id] ? <Image source={authorPhotos[author.id]} style={styles.photo} /> : <View style={[styles.photo, styles.photoPlaceholder]}><Text style={styles.photoInitial}>{author.name.charAt(0)}</Text></View>}</View></View>{author.quotes.map((rawQuote) => { const quote: Quote = { ...rawQuote, authorName: author.name }; const saved = quotes.some((item) => item.id === quote.id); return <View key={quote.id} style={styles.quoteCard}><Text style={styles.quote}>“{quote.text}”</Text><Pressable accessibilityRole="button" accessibilityLabel={saved ? `Remove ${quote.text}` : `Save ${quote.text}`} style={[styles.save, saved && styles.remove]} onPress={() => void (saved ? removeQuote(quote.id) : saveQuote(quote))}><Text style={styles.saveText}>{saved ? 'Remove from My Bank' : '+ Save to My Bank'}</Text></Pressable></View>; })}</ScrollView>;
}
export default function AuthorDetailScreen(): JSX.Element { const { authorId } = useLocalSearchParams<{ authorId: string }>(); return <AuthorDetail authorId={authorId} />; }
const styles = StyleSheet.create({ page: { padding: 20, backgroundColor: colors.cream, flexGrow: 1 }, backButton: { alignSelf: 'flex-start', marginBottom: 16, paddingVertical: 6, paddingHorizontal: 4 }, backButtonText: { color: colors.burntCaramel, fontWeight: '800', fontSize: 15 }, header: { flexDirection: 'row', alignItems: 'center', marginBottom: 22 }, headerText: { flex: 1, paddingRight: 16 }, name: { fontSize: 29, fontWeight: '800', color: colors.chocolate }, bio: { marginTop: 10, fontSize: 16, lineHeight: 23, color: colors.mutedChocolate }, photoSlot: { width: 84, height: 84 }, photo: { width: 84, height: 84, borderRadius: 42 }, photoPlaceholder: { backgroundColor: colors.taupe, alignItems: 'center', justifyContent: 'center' }, photoInitial: { color: colors.white, fontSize: 28, fontWeight: '800' }, quoteCard: { backgroundColor: colors.white, borderRadius: 16, borderColor: colors.border, borderWidth: 1, padding: 18, marginBottom: 14 }, quote: { fontSize: 18, lineHeight: 26, color: colors.chocolate }, save: { alignSelf: 'flex-start', marginTop: 16, backgroundColor: colors.caramel, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 9 }, remove: { backgroundColor: colors.burntCaramel }, saveText: { color: colors.white, fontWeight: '800' } });