import { useMemo, useState } from 'react';
import { FlatList, Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { authorsData } from '@/src/data/authorsData';
import { authorPhotos } from '@/src/data/authorPhotos';
import { colors } from '@/src/theme';

export default function AuthorsScreen(): JSX.Element {
  const [search, setSearch] = useState(''); const authors = useMemo(() => authorsData.filter((author) => author.name.toLowerCase().includes(search.toLowerCase())), [search]);
  return <View style={styles.page}><TextInput accessibilityLabel="Search authors" value={search} onChangeText={setSearch} placeholder="Search authors" placeholderTextColor={colors.taupe} style={styles.search} /><FlatList data={authors} keyExtractor={(author) => author.id} renderItem={({ item }) => <Pressable accessibilityRole="button" style={styles.row} onPress={() => router.push(`/authors/${item.id}`)}><View style={styles.textCol}><Text style={styles.name}>{item.name}</Text><Text style={styles.bio} numberOfLines={1}>{item.bio}</Text></View><View style={styles.photoSlot}>{authorPhotos[item.id] ? <Image source={authorPhotos[item.id]} style={styles.photo} /> : <View style={[styles.photo, styles.photoPlaceholder]}><Text style={styles.photoInitial}>{item.name.charAt(0)}</Text></View>}</View></Pressable>} /></View>;
}
const styles = StyleSheet.create({ page: { flex: 1, padding: 16, backgroundColor: colors.cream }, search: { backgroundColor: colors.white, borderColor: colors.border, borderWidth: 1, borderRadius: 12, padding: 14, marginBottom: 14, fontSize: 16, color: colors.chocolate }, row: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.white, padding: 14, borderRadius: 16, borderWidth: 1, borderColor: colors.border, marginBottom: 10 }, textCol: { flex: 1, paddingRight: 12 }, name: { fontSize: 18, fontWeight: '800', color: colors.chocolate }, bio: { marginTop: 5, color: colors.mutedChocolate, lineHeight: 19 }, photoSlot: { width: 56, height: 56 }, photo: { width: 56, height: 56, borderRadius: 28 }, photoPlaceholder: { backgroundColor: colors.taupe, alignItems: 'center', justifyContent: 'center' }, photoInitial: { color: colors.white, fontSize: 20, fontWeight: '800' } });