import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { QuoteCard } from '@/src/components/QuoteCard';
import { useQuoteBank } from '@/src/hooks/useQuoteBank';
import { colors } from '@/src/theme';

export default function QuoteBankScreen(): JSX.Element {
  const { quotes, quoteOfDay, loading, removeQuote, refreshQuoteOfDay } = useQuoteBank();
  if (loading) return <View style={styles.center}><ActivityIndicator /></View>;
  return <View style={styles.page}><View style={styles.banner}><Text style={styles.kicker}>QUOTE OF THE DAY</Text><Text style={styles.bannerQuote}>{quoteOfDay ? `“${quoteOfDay.text}”` : 'No quotes saved!'}</Text>{quoteOfDay ? <Text style={styles.bannerAuthor}>— {quoteOfDay.authorName}</Text> : <Text style={styles.bannerAuthor}>Save one from Explore to start your daily cycle.</Text>}<Pressable accessibilityRole="button" onPress={() => void refreshQuoteOfDay()}><Text style={styles.next}>Show next quote</Text></Pressable></View>
    <Text style={styles.heading}>My saved quotes</Text>{quotes.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>Your quote bank is empty</Text><Text style={styles.emptyText}>Explore authors and save the words you want to revisit.</Text></View> : <FlatList data={quotes} keyExtractor={(item) => item.id} renderItem={({ item }) => <QuoteCard quote={item} onDelete={() => void removeQuote(item.id)} />} />}</View>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.cream, padding: 16 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.cream }, banner: { backgroundColor: colors.chocolate, borderRadius: 20, padding: 22, marginBottom: 20, shadowColor: colors.chocolate, shadowOpacity: .18, shadowRadius: 12, elevation: 4 }, kicker: { fontWeight: '800', color: '#F4C994', fontSize: 12, letterSpacing: 1.2 }, bannerQuote: { color: colors.white, fontSize: 20, lineHeight: 29, marginTop: 9, fontWeight: '600' }, bannerAuthor: { color: colors.softCream, marginTop: 9 }, next: { color: '#F4C994', marginTop: 16, fontWeight: '800' }, heading: { fontSize: 22, fontWeight: '800', marginBottom: 12, color: colors.chocolate }, empty: { alignItems: 'center', padding: 30, backgroundColor: colors.white, borderRadius: 16, borderWidth: 1, borderColor: colors.border }, emptyTitle: { fontSize: 18, fontWeight: '800', color: colors.chocolate }, emptyText: { color: colors.mutedChocolate, textAlign: 'center', marginTop: 8, lineHeight: 21 } });
