import { useState } from 'react';
import { Alert, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useQuoteBank } from '@/src/hooks/useQuoteBank';

const pad = (value: number): string => value.toString().padStart(2, '0');
export default function SettingsScreen(): JSX.Element {
  const { notificationTime, updateNotificationTime } = useQuoteBank(); const [hour, setHour] = useState(String(notificationTime.hour)); const [minute, setMinute] = useState(pad(notificationTime.minute));
  const save = async (): Promise<void> => { const h = Number(hour); const m = Number(minute); if (!Number.isInteger(h) || !Number.isInteger(m) || h < 0 || h > 23 || m < 0 || m > 59) { Alert.alert('Use a valid 24-hour time', 'Hour: 0–23. Minute: 0–59.'); return; } await updateNotificationTime({ hour: h, minute: m }); Alert.alert('Saved', `Your daily quote will arrive at ${pad(h)}:${pad(m)}.`); };
  return <View style={styles.page}><Text style={styles.title}>Daily delivery</Text><Text style={styles.copy}>Choose when your local daily quote notification should arrive. Notifications gracefully do nothing on web if permission is unavailable.</Text><View style={styles.time}><TextInput accessibilityLabel="Notification hour" keyboardType="number-pad" maxLength={2} value={hour} onChangeText={setHour} style={styles.input} /><Text style={styles.colon}>:</Text><TextInput accessibilityLabel="Notification minute" keyboardType="number-pad" maxLength={2} value={minute} onChangeText={setMinute} style={styles.input} /></View><Pressable accessibilityRole="button" onPress={() => void save()} style={styles.button}><Text style={styles.buttonText}>Save notification time</Text></Pressable>{Platform.OS === 'web' ? <Text style={styles.note}>Web demo: notifications depend on your browser permission.</Text> : null}</View>;
}
const styles = StyleSheet.create({ page: { flex: 1, padding: 20, backgroundColor: '#f5f7fa' }, title: { fontSize: 26, fontWeight: '800', color: '#263238' }, copy: { marginTop: 10, color: '#546e7a', lineHeight: 22 }, time: { flexDirection: 'row', alignItems: 'center', marginTop: 28 }, input: { backgroundColor: '#fff', width: 74, padding: 14, borderRadius: 10, textAlign: 'center', fontSize: 20 }, colon: { fontSize: 25, fontWeight: '800', marginHorizontal: 9 }, button: { backgroundColor: '#00796b', padding: 15, borderRadius: 10, marginTop: 20, alignItems: 'center' }, buttonText: { color: '#fff', fontWeight: '800' }, note: { marginTop: 20, color: '#607d8b', fontSize: 13 } });
